#!/bin/sh

# CXX is a compilation driver, so we should check which stage of compilation
# is actually running and select which flags to provide. This makes no
# difference for GCC, but e.g. clang warns when a flag is provided that is
# unused 

run_it() {
	echo "[CXX $PWD]:" "$@"
	exec "$@"
}

running_pp=false
running_cc=false

# Guess what is actually running...
for flag in "$@"; do
	case "$flag" in
		-E) running_pp=true ;;
		-c|-S) running_cc=true ;;
		*) ;;
	esac
done

# ...and pass the correct flags
if $running_pp; then
	run_it $HELENOS_CROSS_PATH/$HSCT_REAL_CXX $HSCT_CXXPPFLAGS "$@"
elif $running_cc; then
	run_it $HELENOS_CROSS_PATH/$HSCT_REAL_CXX $HSCT_CXXPPFLAGS $HSCT_CXXFLAGS -Wno-narrowing "$@"
else
	run_it $HELENOS_CROSS_PATH/$HSCT_REAL_CXX $HSCT_CXXPPFLAGS $HSCT_CXXFLAGS -Wno-narrowing $HSCT_LDFLAGS "$@" $HSCT_LDLIBS
fi
